spring.application.name=Task-time-tracker
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/task_time_tracker
spring.datasource.username=postgres
spring.datasource.password=7magic2024zer0
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

docker.client.strategy=org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy
spring.sql.init.data-locations=classpath:insert-data.sql
