spring.application.name=Task-time-tracker
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/task_time_tracker
spring.datasource.username=postgres
spring.datasource.password=7magic2024zer0
spring.datasource.driver-class-name=org.postgresql.Driver

#mybatis.mapper-locations=classpath:mapper/*.xml
#mybatis.type-aliases-package=ru.shaporenko.intern.task_time_tracker.entity

spring.sql.init.mode=always
spring.datasource.initialization-mode=always